---
################################################################
###                    *** WARNING ***
################################################################
###
### ALMOST EVERYTHING REQUESTED IN THIS FILE ARE CONFIDENTIAL CREDENTIALS
### IF YOU POST THIS FILE ONLINE (such as on GitHub) YOUR BOT COULD BE COMPROMISED
###
###
### Use a proper text editor when editing this file, for example Sublime.
### Do not use tab characters in this file, use plain spaces.
###
### Keep at least one space after a colon, like so:
###
###   key: value
###
###
### Never edit or add a value to lines that have no default value, like:
###
###   credentials:
###
### Just leave them be. A default value may be an empty string like so: ""
###
###
### You can wrap most values into quotation marks, except numbers and booleans:
###
###   someUrl: "http://example.com"
###   someToken: "123.qwe.456[DFG="
###   somePortNumber: 22
###   useSomeFeature: true
###
###
### You can have a list of things like this:
###
###   listOfStrings: ["string1", "string2", "string3"]
###
### or like this:
###
###   listOfStrings:
###     - "string1"
###     - "string2"
###     - "string3"
###
###
### More information on correctly formatting yaml files: http://www.yaml.org/start.html


################################################################
###                 Basic configuration
################################################################

config:
  development:       true         # Set this to false for selfhosting. If you leave this enabled and complain about weird
                                  # things happening to your bot in the selfhosting chat you will be publicly taunted.
  prefix:            '<<'         # Default prefix used by the bot
  botAdmins:         []           # Add comma separated userIds and roleIds that should have access to bot admin commands. Find role ids with the ;;roleinfo command
  botOwners:         []           # Add comma separated userIds that should have access to bot OWNER commands. Mainly intended for bots that belong to teams
  autoBlacklist:     true         # Set to true to automatically blacklist users who frequently hit the rate limits
  game:              ""           # Set the displayed game/status. Leave empty quote marks for the default status
  continuePlayback:  false        # Set to true to force the player to continue playback even if left alone
  shardCount: 1                   # The number of shards this bot supports. Leave at 1 unless you know what you are doing.
# ratelimit:
#   ipBlocks: ["127.0.0.1/31", "127.0.0.3/32", "..."] # list of ip blocks
#   excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
#   strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
#   searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing

server:
  port: 1356                      # Change the port of the API FredBoat exposes
spring:
  main:
    web-application-type: none    # Set this to "servlet", "reactive" or "none", whichever ends up working, to enable/disable the FredBoat API.
  output:
    ansi:
      enabled: detect             # for developers: setting this to "always" will force colored logs in your console


audio-sources:
  enableYouTube:     true         # Set to true to enable playing YouTube links
  enableSoundCloud:  true         # Set to true to enable playing SoundCloud links
  enableBandCamp:    true         # Set to true to enable playing BandCamp links
  enableTwitch:      true         # Set to true to enable playing Twitch links
  enableVimeo:       true         # Set to true to enable playing Vimeo links
  enableMixer:       true         # Set to true to enable playing Mixer links
  enableSpotify:     true         # Set to true to enable playing Spotify links
  enableLocal:       false        # Set to true to enable playing local files
  enableHttp:        false        # Set to true to enable playing direct links


################################################################
###                 Essential credentials
################################################################

backend:
  quarterdeck:
    # Host address of your quarterdeck backend, including port unless you are using a reverse proxy.
    # Example: https://such.example.com:4269/
    # No need set the host when running Quarterdeck in Docker.
    host: ""
    # Credentials used to authenticate to with Quarterdeck.
    # By default Quarterdeck uses docker:docker when using our docker-compose files
    user: "docker"
    pass: "docker"


credentials:
  # Used by the ;;split and ;;np commands. Must be hooked up to the Youtube Data API.
  # You can add additional keys in case you are running a big bot
  # How to get the key: https://developers.google.com/youtube/registering_an_application
  # Add your google API key between the quotation marks
  googleApiKeys:
    - "PutYourGoogleAPIKeyHere"

  # The preferred way of setting the token is described in ./common.yml
  #discordBotToken: ""



################################################################
###                     Optional APIs
################################################################

  # Used to access imgur galleries for some RandomImageCommands
  # Acquired from here: https://api.imgur.com/oauth2/addclient
  # Choose an option that does not require an Authorization callback URL
  imgurClientId:  ""


  # Used by ;;export command. Only set this if you have a https://wastebin.party account.
  wastebinUser:     ""
  wastebinPass:     ""

  # Used to retrieve Spotify playlists
  # Get them from here: https://developer.spotify.com/my-applications
  spotifyId:      ""
  spotifySecret:  ""


  # Used by ;;weather command.
  # Get them from: http://openweathermap.org/appid
  openWeatherKey: ""

  # Error aggregation service https://sentry.io/
  sentryDsn:      ""



event-logger:
  # Webhooks to Discord channels that will post some guild stats and shard status changes
  # More information on webhooks: https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  # Example: "https://canary.discordapp.com/api/webhooks/1234567890/QWERTZUIOPasdfghjklYXCVBNM" (no, this one will not work)
  eventLogWebhook:            "" # webhook url for connect / disconnect events
  eventLogInterval:           1  # interval at which connect / disconnect events are posted in minutes
  guildStatsWebhook:          "" # webhook url for guild stats
  guildStatsInterval:         60 # interval at which guild stats are posted in minutes


# Lavalink is used for playing music.
# More on Lavalink: https://github.com/Frederikam/Lavalink
# If fully commented out, FredBoat will automatically guess that Lavalink is hosted locally at port 2333
#lavalink:
#  nodes:
#    - name : "local"
#      host : "ws://localhost:2333"
#      pass : "youshallnotpass"
#    - name : "remote1"
#      host : "ws://192.168.1.20:5556"
#      pass : "youshallnotpass"
#    - name : "remote2"
#      host : "ws://lavalink.example.com:5557"
#      pass : "youshallnotpass"

# tune these according to your needs, or just leave them as is.
logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    fredboat: DEBUG
    com.fredboat: DEBUG
    net.dv8tion: DEBUG
