################################################################################
###                           Table of contents
################################################################################
# docker-compose.yml - Docker configuration for all services but FredBoat. For development
# selfhosting.yml    - The same file but *including* FredBoat
# common.yml         - Contains essential configuration for FredBoat and Sentinel
# fredboat.yml       - FredBoat config
# lavalink.yml       - Lavalink config
# quarterdeck.yml    - Quarterdeck config
#

################################################################################
###                  Selfhosting FredBoat with docker-compose
################################################################################
###
### Use a proper text editor like Sublime when editing this file
### Do not use tab characters in this file, only spaces are allowed. Don't add or delete unnecessary spaces.
### More information on correctly formatting yaml files: http://www.yaml.org/start.html
###
### For further information on running FredBoat visit https://fredboat.com/docs/selfhosting or the #selfhosting channel
### on the FredBoat Hangout Discord server: https://discord.gg/cgPFW4q


version: '3' # This is not the FredBoat version, do not touch this line.
services:

  ################################################################################
  ##                               Database
  ################################################################################
  db:
    image: fredboat/postgres:latest
    #image: fredboat/postgres:arm64v8   #for (some) arm based machines
    #build: ./FredBoat/docker/database/ #useful alternative for developers
    restart: always
    labels:
    - "com.centurylinklabs.watchtower.enable=true"

    # WINDOWS ONLY: if you are running under windows you need to comment out the following two lines:
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

    # WINDOWS ONLY: if you are running under windows and want to take manual backups of the database
    # via a docker volume, uncomment the following two lines and read the snippet at the bottom of this file
    #volumes:
    #- postgres-data-volume:/var/lib/postgresql/data

  ################################################################################
  ##                               RabbitMQ
  ################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - 127.0.0.1:5672:5672   # The broker
    - 127.0.0.1:15672:15672 # Web UI
    labels:
    - "com.centurylinklabs.watchtower.enable=true"

  ################################################################################
  ##                               Lavalink
  ################################################################################
  lavalink:
    image: fredboat/lavalink:master
    restart: always
    labels:
    - "com.centurylinklabs.watchtower.enable=true"
    ports:
    - 127.0.0.1:2333:2333
    volumes:
    - ./lavalink.yml:/opt/Lavalink/application.yaml
    - ./lavalink_logs:/opt/Lavalink/logs
    # Need a bigger memory size or any other custom JVM args? Edit the line below accordingly
    entrypoint: java -Xmx128m -jar Lavalink.jar

  ################################################################################
  ##                               Sentinel
  ################################################################################
  sentinel:
    image: fredboat/sentinel:dev
    restart: on-failure:3
    depends_on:
    - rabbitmq
    labels:
    - "com.centurylinklabs.watchtower.enable=true"
    volumes:
    - ./sentinel_logs:/opt/sentinel/logs
    - ./common.yml:/opt/sentinel/common.yml
    environment:
    - "SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq"
    # Need a bigger memory size or any other custom JVM args? Uncomment and edit the line below accordingly
    #entrypoint: java -Xmx512m -jar sentinel.jar
    logging:
      options:
        max-size: "1g"
        max-file: "1"

  ################################################################################
  ##                     Quarterdeck (Database Backend)
  ################################################################################
  quarterdeck:
    # versions (example: v2) receive continous non-breaking (best effort) updates via watchtower. switching between versions
    # (example: going from v2 to v3) usually requires manual migration. what exactly is needed is published on the
    # FredBoat selfhosting website and/or the selfhosters channel (see top of this file for how to get to these places)
    # Once you use the dev branch, you may not be able to go back to stable without deleting your database.
    # To run on (some) arm based machines, prepend the tag with arm64v8-, for example: fredboat/quarterdeck:arm64v8-dev-v1
    # NOTE: Don't use the dev-v1 build unless otherwise noted as it has breaking changes with the other builds.
    #image: fredboat/quarterdeck:dev-v1
    image: fredboat/quarterdeck:stable-v1
    restart: always
    labels:
    - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
    - db
    ports:
    - 127.0.0.1:4269:4269
    volumes:
    - ./quarterdeck.yml:/opt/Quarterdeck/quarterdeck.yaml
    - ./quarterdeck_logs:/opt/Quarterdeck/logs

    # Need a bigger memory size or any other custom JVM args? Edit the list below accordingly
    entrypoint:
    - java
    - -Xmx128m
    - -jar
    - Quarterdeck.jar
    - >
      --spring.application.json={"security": {"admins": [{"name": "docker", "pass": "docker"}]}}

  ################################################################################
  ##                               FredBoat
  ################################################################################
  bot:
    # for choosing between stable or dev, read the paragraph above in the Quarterdeck section
    # IMPORTANT: both quarterdeck and fredboat need to either be on the stable, or on the dev branch
    # To run on (some) arm based machines, prepend the tag with arm64v8-, for example: fredboat/fredboat:arm64v8-dev-v3
    image: fredboat/fredboat:dev-v4
    #build: ./FredBoat #useful alternative for developers

    restart: on-failure:3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - quarterdeck
      - sentinel
      - lavalink
    ports:
      - 1356:1356
    environment:
      - "SPRING_RABBITMQ_ADDRESSES=amqp://guest:guest@rabbitmq"
    volumes:
      - ./fredboat.yml:/opt/FredBoat/fredboat.yml
      - ./common.yml:/opt/FredBoat/common.yml
      - ./fredboat_logs:/opt/FredBoat/logs
      - ./music_persistence:/opt/FredBoat/music_persistence
      # If your music directory looks like this: /home/user/music/directory/rickroll.mp3 or C:\Users\user\Music\rickroll.mp3
      # you will be able to play that file with this command: <<play file://music/rickroll.mp3
      # Linux example:
      #- /home/your_user_name/music:/opt/FredBoat/music
      # Windows example:
      #- C:\Users\your_user_name\Music:/opt/FredBoat/music

    # Need a bigger memory size or any other custom JVM args? uncomment and edit the line below accordingly
    #entrypoint: java -Xmx256m -jar FredBoat.jar


  ################################################################################
  ##                         Automatic updates
  ################################################################################
  # if you want automatic updates, uncomment the watchtower lines below
  # watchtower is not yet officially available for arm64v8. See https://github.com/v2tec/watchtower/pull/178 for progress
  # but you can try using napstr/watchtower:arm64v8-latest

  #watchtower:
  #  image: v2tec/watchtower
  #  restart: on-failure:3
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --cleanup --label-enable --interval 300 #seconds


  ################################################################################
  ##                         Windows stuff
  ################################################################################

# WINDOWS ONLY: If you are running on Windows and want to be able to backup the postgres data volume, run
#
#   docker volume create --name postgres-data-volume -d local
#
# and uncomment the following lines:
# See also the WINDOWS ONLY hints in the database section

#volumes:
#  postgres-data-volume:
#    external: true
